package dbg28

import org.junit.Assert._
import org.junit.{Before, Test}
/**
  * EECS 293
  * Created by Daniel on 10/20/2016.
  * dbg28@case.edu
  */
class SetWrapperTest {

  // Fields

  var tester: TestTool = _

  /**
    * Helper method to
    * @return
    */
  @Before
    def createDatabaseWithNinjas(): Unit = {
      tester = new TestTool().createDatabaseWithNinjas()
    }


  /**
    * getOpponents is not an autogenerated getter, so it must be tested
    *  Satisfies: Dataflow
    *  N/A: Branching, Boundary, Compound Boundary,
    *  N/A: Bad Data, Good Data, Boundary Analysis
    */
  @Test
  def testGetOpponents(): Unit = {


  }
}
